config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'subjects#index'

  resources :subjects, only: %i[index show]
  resources :votes, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :subject_choices
  has_many :votes, through: :subject_choices

  def voted_choices
    @voted_choices ||= subject_choices.sort_by { |c| c.votes.size * -1 }
  end
end

app/models/subject_choice.rb
class SubjectChoice < ApplicationRecord
  belongs_to :subject
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :subject
  belongs_to :subject_choice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
    @vote = Vote.find_or_initialize_by(session_id: session[:session_id], subject_id: params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    subject_choice = SubjectChoice.find(vote_params[:subject_choice_id])
    @vote = Vote.find_or_initialize_by(session_id: session[:session_id], subject_id: subject_choice.subject_id)
    @vote.subject_choice_id = subject_choice.id
    if @vote.save
      subject = Subject.find(subject_choice.subject_id)
      @vote.broadcast_replace_to subject, target: 'voting_result', partial: 'subjects/voting_result', locals: { subject: subject }
    end
  end

  private

  def vote_params
    params
      .require(:vote)
      .permit(:subject_choice_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireVote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subjects/_voting_result.html.slim
#voting_result
  - if subject.votes.blank?
    p まだ誰も投票していません。
  - else
    ul
      - subject.voted_choices.each.with_index(1) do |voted_choice, index|
        li = "第#{index}位 #{voted_choice.name}  #{voted_choice.votes.size}票"

app/views/subjects/index.html.slim
.container
  h1
    | 現在、以下の投票を受付中です。

  .block
    ul
      - @subjects.each do |subject|
        li = link_to subject.title, subject_path(subject.id)

app/views/subjects/show.html.slim
= turbo_stream_from @subject
.container
  h1 = "お題: #{@subject.title}"

  .block.vote_form
    = form_for @vote,
            url: votes_path,
            method: :post,
            html: { data: { turbo_frame: 'votes', controller: 'votes', action: 'input->votes#submit' } } do |f|

      - @subject.subject_choices.each do |choice|
        label
          = f.radio_button :subject_choice_id, choice.id, class: ''
          = choice.name

  .block.result
    p 投票の結果
    = render partial: 'subjects/voting_result', locals: { subject: @subject }